name: My first workflow

on: push

jobs:
  first_job:
      runs-on: ubuntu-latest
      step:
      -name: checkout
        - uses: actions/checkout@v7
      
      -name: First step
        run : echo 'My first step'
      
      -name: list of files 
        run : ls 
